CREATE DATABASE ATAHUALPA_DBA;
GO
USE ATAHUALPA_DBA;
GO

CREATE TABLE PRODUCTO(
ID_PROD INT IDENTITY(1000,100) NOT NULL,
NOMBRE VARCHAR(150) NOT NULL,
DESCRIPCION VARCHAR(255) DEFAULT '---',
PRECIO_COMP DECIMAL(5,2) NOT NULL,
PRECIO_VENT DECIMAL(5,2) NOT NULL,
STOCK INT NOT NULL,
ID_PROV INT NOT NULL,
UNIDAD INT NOT NULL,
FECHA_INGRESO DATE,
ACTIVO BIT DEFAULT 1 NOT NULL,
PRIMARY KEY(ID_PROD)
);
GO

CREATE TABLE TIPO_UNIDAD(
ID_UNI INT IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(150) NOT NULL,
PRIMARY KEY(ID_UNI)
);
GO

CREATE TABLE PROVEEDOR(
ID_PROV INT IDENTITY(100,100) NOT NULL,
NOMBRE VARCHAR(255) NOT NULL,
RUC VARCHAR(11) DEFAULT '00000000000',
DIRECCION VARCHAR(255) DEFAULT '---' NOT NULL,
TELEFONO VARCHAR(11) DEFAULT '000000000' NOT NULL,
EMAIL VARCHAR(100) DEFAULT 'EMAIL@DOMINIO.COM' NOT NULL,
DESCRIPCION VARCHAR(255) DEFAULT 'PROVEEDOR GENERAL' NOT NULL,
FECHA_REGISTRO DATE,
ACTIVO BIT DEFAULT 1 NOT NULL,
PRIMARY KEY(ID_PROV)
);
GO

CREATE TABLE CLIENTE(
ID_CLI INT IDENTITY(100,110) NOT NULL,
NOMBRES VARCHAR(150) NOT NULL,
APELLIDOS VARCHAR(150) NOT NULL,
DNI VARCHAR(20) DEFAULT '00000000' NOT NULL,
DIRECCION VARCHAR(255) DEFAULT '---' NOT NULL,
EMAIL VARCHAR(100) DEFAULT 'EMAIL@DOMINIO.COM' NOT NULL,
TELEFONO VARCHAR(11) DEFAULT '000000000' NOT NULL,
FECHA_REGISTRO DATE,
ACTIVO BIT DEFAULT 1 NOT NULL,
PRIMARY KEY(ID_CLI)
);
GO

CREATE TABLE COMPROBANTE(
ID_COMP INT IDENTITY(100000,1) NOT NULL,
TIPO VARCHAR(4) DEFAULT 'BOL' NOT NULL,
EMISION DATETIME NOT NULL,
SUBTOTAL DECIMAL NOT NULL,
TOTAL DECIMAL NOT NULL,
IGV DECIMAL NOT NULL,
PAGADO BIT DEFAULT 1 NOT NULL,
PRIMARY KEY(ID_COMP)
);
GO

CREATE TABLE COMPRA(
ID_COMP INT NOT NULL,
ID_CLI INT NOT NULL,
PRIMARY KEY(ID_COMP,ID_CLI)
);
GO

CREATE TABLE COMPROBANTE_PROD(
ID_COMP INT NOT NULL,
ID_PROD INT NOT NULL,
PRIMARY KEY(ID_COMP,ID_PROD)
);
GO

CREATE TABLE USUARIO(
ID_USR INT IDENTITY(10,10) NOT NULL,
USUARIO VARCHAR(20) NOT NULL,
CONTRASENA VARCHAR(255) NOT NULL,
NOMBRES VARCHAR(150) NOT NULL,
APELLIDOS VARCHAR(150) NOT NULL,
EMAIL VARCHAR(100) DEFAULT 'EMAIL@DOMINIO.COM' NOT NULL,
TELEFONO VARCHAR(11) DEFAULT '000000000' NOT NULL,
FECHA_REGISTRO DATE,
ACTIVO BIT DEFAULT 1 NOT NULL,
PERMISOS INT DEFAULT 0 NOT NULL,
PRIMARY KEY(ID_USR)
)
GO
------RELACIONES.
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PROD_PROV FOREIGN KEY(ID_PROV) REFERENCES PROVEEDOR(ID_PROV);
GO
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PROD_UNI FOREIGN KEY(UNIDAD) REFERENCES TIPO_UNIDAD(ID_UNI);
GO
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_COMP FOREIGN KEY(ID_COMP) REFERENCES COMPROBANTE(ID_COMP);
GO
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_CLI FOREIGN KEY(ID_CLI) REFERENCES CLIENTE(ID_CLI);
GO
ALTER TABLE COMPROBANTE_PROD ADD CONSTRAINT FK_CP_COMP FOREIGN KEY(ID_COMP) REFERENCES COMPROBANTE(ID_COMP);
GO
ALTER TABLE COMPROBANTE_PROD ADD CONSTRAINT FK_CP_PROD FOREIGN KEY(ID_PROD) REFERENCES PRODUCTO(ID_PROD);


-----DATOS.

-----UNIDAD.
INSERT INTO TIPO_UNIDAD(NOMBRE) VALUES('UND.'),('DOCENA'),('CAJA'),('BOTELLA 100ML'),('BOTELLA 500ML'),('BOTELLA 1LT'),('BOTELLA 2LT'),('GALON 4LT'),('BOLSA 25KG'),('SACO 20KG'),('SACO 25KG'),('SACO 42KG');

------PROVEEDOR
INSERT INTO PROVEEDOR(NOMBRE, RUC, DIRECCION, TELEFONO, EMAIL, FECHA_REGISTRO,ACTIVO) VALUES('ACEROS AREQUIPA','20370146994','Car. Panamericana Sur Nro. 241 Panamericana Sur','994615443','VENTAS@ACEROS_AREQUIPA.COM','2023-09-17',1);
INSERT INTO PROVEEDOR(NOMBRE, RUC, DIRECCION, TELEFONO, EMAIL, FECHA_REGISTRO,ACTIVO) VALUES('FERROPOLIS PE','20601968607','Mza. G Lote. 01 A.H. los Alamos de Ventanil','996192665','VENTAS@FERROPOLIS.NET','2023-09-16',1);
-----PRODUCTO
INSERT INTO PRODUCTO(NOMBRE,PRECIO_COMP,PRECIO_VENT,STOCK,ID_PROV,UNIDAD,FECHA_INGRESO) VALUES('CLAVO ACERADO 1/2"',3.20,4.50,50,200,2,'2023-09-17'),('CLAVO ACERADO 2"',4,5,50,200,2,'2023-09-17'),('CEMENTO SOL',16,24,120,200,12,'2023-09-17'),('CEMENTO ANDINO',15,22,180,200,12,'2023-09-17'),('BARRA DE CONSTRUCCIÓN SP 1/2" x 9MTS',38,42.5,50,100,1,'2023-09-16'),('BARRA DE CONSTRUCCIÓN SP 6MM x 9MTS',7,10,75,100,1,'2023-09-16'),('BARRA DE CONSTRUCCIÓN SP 3/4" x 9MTS',80,90.5,20,100,1,'2023-09-16'),('BARRA DE CONSTRUCCIÓN SP 12MM x 9MTS',30,37,45,100,1,'2023-09-15'),('ALAMBRE CORRUGADO 4.7MM x 8.80MTS',3,5.50,100,100,1,'2023-09-16');
