//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atahualpa_ferresys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTE
    {
        public COMPROBANTE()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int ID_COMP { get; set; }
        public string TIPO { get; set; }
        public System.DateTime EMISION { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal TOTAL { get; set; }
        public decimal IGV { get; set; }
        public bool PAGADO { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
