//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atahualpa_ferresys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.COMPROBANTE = new HashSet<COMPROBANTE>();
        }
    
        public int ID_PROD { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_COMP { get; set; }
        public decimal PRECIO_VENT { get; set; }
        public int STOCK { get; set; }
        public int ID_PROV { get; set; }
        public int UNIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual TIPO_UNIDAD TIPO_UNIDAD { get; set; }
        public virtual ICollection<COMPROBANTE> COMPROBANTE { get; set; }
    }
}
