//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atahualpa_ferresys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_UNIDAD
    {
        public TIPO_UNIDAD()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int ID_UNI { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
